server:
  port: 8081
spring:
  application:
    name: satellite-launcher
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    ###for memory DB
    url:  jdbc:h2:mem:satellite_launcher
    ## for file FB
    #url:  jdbc:h2:file:/Users/ankurmishra/dbfile/satellite_launchers

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
  config:
    location: file:./config/
